services:
  - type: web
    name: zedchess-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SOCKETIO_ASYNC_MODE
        value: eventlet
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@zedchess.app
      - key: ADMIN_PASSWORD
        generateValue: true